# coding: utf-8

"""
    IP Address Management API

    The IPAM/DHCP Application is a BloxOne DDI service providing IP address management and DHCP protocol features. The IPAM component provides visibility into and provisioning tools to manage networking spaces, monitoring and reporting of entire IP address infrastructures, and integration with DNS and DHCP protocols. The DHCP component provides DHCP protocol configuration service with on-prem host serving DHCP protocol. It is part of the full-featured, DDI cloud solution that enables customers to deploy large numbers of protocol servers to deliver DNS and DHCP throughout their enterprise network.     # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class IpamsvcHAGroupHost(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'host': 'str',
        'port': 'int',
        'role': 'str'
    }

    attribute_map = {
        'host': 'host',
        'port': 'port',
        'role': 'role'
    }

    def __init__(self, host=None, port=None, role=None):  # noqa: E501
        """IpamsvcHAGroupHost - a model defined in Swagger"""  # noqa: E501

        self._host = None
        self._port = None
        self._role = None
        self.discriminator = None

        self.host = host
        if port is not None:
            self.port = port
        if role is not None:
            self.role = role

    @property
    def host(self):
        """Gets the host of this IpamsvcHAGroupHost.  # noqa: E501

        The resource identifier.  # noqa: E501

        :return: The host of this IpamsvcHAGroupHost.  # noqa: E501
        :rtype: str
        """
        return self._host

    @host.setter
    def host(self, host):
        """Sets the host of this IpamsvcHAGroupHost.

        The resource identifier.  # noqa: E501

        :param host: The host of this IpamsvcHAGroupHost.  # noqa: E501
        :type: str
        """
        if host is None:
            raise ValueError("Invalid value for `host`, must not be `None`")  # noqa: E501

        self._host = host

    @property
    def port(self):
        """Gets the port of this IpamsvcHAGroupHost.  # noqa: E501

        RO field: HA port.  # noqa: E501

        :return: The port of this IpamsvcHAGroupHost.  # noqa: E501
        :rtype: int
        """
        return self._port

    @port.setter
    def port(self, port):
        """Sets the port of this IpamsvcHAGroupHost.

        RO field: HA port.  # noqa: E501

        :param port: The port of this IpamsvcHAGroupHost.  # noqa: E501
        :type: int
        """

        self._port = port

    @property
    def role(self):
        """Gets the role of this IpamsvcHAGroupHost.  # noqa: E501


        :return: The role of this IpamsvcHAGroupHost.  # noqa: E501
        :rtype: str
        """
        return self._role

    @role.setter
    def role(self, role):
        """Sets the role of this IpamsvcHAGroupHost.


        :param role: The role of this IpamsvcHAGroupHost.  # noqa: E501
        :type: str
        """

        self._role = role

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(IpamsvcHAGroupHost, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, IpamsvcHAGroupHost):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
